version: "2"
services:
  md2html:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8083:80"
    volumes:
      - ./src:/var/www/html
      - ../md2html-php:/home/customer/www/swharden.com/gitRepos/md2html-php
