name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: HTTP Request
        run: curl --user "deploy:${{ secrets.DEPLOY_PASSWORD }}" https://swharden.com/scottplot/deploy/
